### ISSUE TITLE
Better dev environment

### ISSUE THREAD

**Issue by friedow** [dot-base/dot-base#11]
### 📦 Describe the Goal
As a developer I want to test all code during development in a full dot.base setup. Howevern, many development PCs don't have sufficient RAM and CPU to host a full dot.base setup, a browser, a terminal and vs code. Thus, I suggest providing every developer with a development instance running on an intranet server. 

### 🚚 Steps Towards this Goal
- [ ] Intranet server to host development dot.base instances
- [ ] Instances should be as close to the production setup as possible.
- [ ] Developers should be able to connect to specific containers in an instance using VS code.
- [ ] All containers should expose a debugger endpoint

**Comment by mecklenburg** [comment]
Please also look into https://github.com/dot-base/old-dot-base/issues#issue-1075846470 for more Info.

**Comment by rti** [comment]
implemented in https://github.com/dot-base/deployments
